// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7nCFCI0o4RpCihQFvJi5Zet2szmA7e_U',
    appId: '1:39143720854:web:e2a653f83176ae80ba3fb7',
    messagingSenderId: '39143720854',
    projectId: 'newapp-bd55011a',
    authDomain: 'newapp-bd55011a.firebaseapp.com',
    storageBucket: 'newapp-bd55011a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1D99SzMiF6V8YSZJk4139olzfoPrfun0',
    appId: '1:39143720854:android:9fd455341ebeb46eba3fb7',
    messagingSenderId: '39143720854',
    projectId: 'newapp-bd55011a',
    storageBucket: 'newapp-bd55011a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY5ZhQD28CN7KqTAZZE45o_sVJLUa4uIQ',
    appId: '1:39143720854:ios:9f734bb895604265ba3fb7',
    messagingSenderId: '39143720854',
    projectId: 'newapp-bd55011a',
    storageBucket: 'newapp-bd55011a.firebasestorage.app',
    iosBundleId: 'com.example.GuGuGaGa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY5ZhQD28CN7KqTAZZE45o_sVJLUa4uIQ',
    appId: '1:39143720854:ios:9f734bb895604265ba3fb7',
    messagingSenderId: '39143720854',
    projectId: 'newapp-bd55011a',
    storageBucket: 'newapp-bd55011a.firebasestorage.app',
    iosBundleId: 'com.example.GuGuGaGa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7nCFCI0o4RpCihQFvJi5Zet2szmA7e_U',
    appId: '1:39143720854:web:5209e76749b8716bba3fb7',
    messagingSenderId: '39143720854',
    projectId: 'newapp-bd55011a',
    authDomain: 'newapp-bd55011a.firebaseapp.com',
    storageBucket: 'newapp-bd55011a.firebasestorage.app',
  );
}
