import { Router } from 'express';
import adminAuthRoute from './admin/admin-auth.route.js';
import branchRoute from './admin/branch.route.js';
import categoryRoute from './admin/category.route.js';
import comboRoute from './admin/combo.route.js';
import dashboardRoute from './admin/dashboard.route.js';
import driverRoute from './admin/driver.route.js';
import orderRoute from './admin/order.route.js';
import productRoute from './admin/product.route.js';
import userRoute from './admin/user.route.js';
const router = Router();
router.use('/auth', adminAuthRoute);
router.use('/branches', branchRoute);
router.use('/categories', categoryRoute);
router.use('/combos', comboRoute);
router.use('/dashboard', dashboardRoute);
router.use('/drivers', driverRoute);
router.use('/orders', orderRoute);
router.use('/products', productRoute);
router.use('/users', userRoute);
export default router;
